Base
platanus/the-store pull request #1
Opened 2022-11-21 17:50 UTC by gmq

## Contexto
​
Aplicación sandbox para trainees

## Qué se esta haciendo

- Se agrega modelos de compras e items (productos) con endpoints
- Para acceder a las compras hay que estar autenticado, no así con los items.

2022-11-22 19:23 UTC, difernandez requested changes
Le echaría un ojo a lo de hound, pa que el proyecto parta sin warnings de linter, puede que se me hayan pasado otras cosas

2022-11-22 19:23 UTC, difernandez commented on spec/factories/purchases.rb
> +  end
Se podría omitir los bloques:
```
  factory :purchase do
    user
    item
  end
```

2022-11-22 19:23 UTC, difernandez commented on app/models/user.rb
> +  has_many :purchases
con esto caché que no está funcionando hound en el proyecto, acá te habría molestado porque falta el `dependent:`

2022-11-22 19:23 UTC, difernandez commented on lib/fake_data_loader.rb
>    end
Duda más general: cachas por qué hacemos estas cosas en este módulo en vez de directo en las seeds?

2022-11-22 19:28 UTC, gmq commented on lib/fake_data_loader.rb
>    end
Por lo que me acuerdo, creo que es para diferenciar entre lo que es 100% necesario para que funcione la app y lo que solo es necesario para hacer más fácil el desarrollo. Tal vez @ldlsegovia tiene una respuesta más clara.

2022-11-22 19:52 UTC, monkeyci commented on lib/fake_data_loader.rb
> +      puts "user: #{user.email} - password: #{USER_PASSWORD}"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2022-11-22 19:59 UTC, gmq commented
Ahí está hound, el test que no pasa es de front 🤔

2022-11-23 13:44 UTC, difernandez approved these changes

2022-11-23 13:45 UTC, merged